import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          // App
          'app_title': 'Calculator App',
          'home': 'Home',

          // Home Page
          'open_calculator': 'Open Calculator',
          'calculator_app_title': 'Calculator Application',

          // Calculator Page
          'calculator': 'Calculator',
          'error': 'Error',
          'clear': 'C',
          'sign': '±',
          'percent': '%',
          'divide': '÷',
          'multiply': '×',
          'subtract': '-',
          'add': '+',
          'equals': '=',
          'zero': '0',
          'one': '1',
          'two': '2',
          'three': '3',
          'four': '4',
          'five': '5',
          'six': '6',
          'seven': '7',
          'eight': '8',
          'nine': '9',
          'dot': '.',

          // Chat Page
          'chat_title': 'AI Chat',
          'chat_ai_name': 'Xiao Yun',
          'chat_ai_title': 'AI Assistant',
          'chat_welcome_message': 'What kind of card would you like to apply for?',
          'chat_option_credit_card': 'Credit Card',
          'chat_option_debit_card': 'Debit Card',
          'chat_option_savings_card': 'Savings Card',
          'chat_ai_disclaimer': 'Content generated by AI, please refer to actual situation',
          'chat_input_placeholder': 'Please enter your question',
          'chat_what_card_question': 'What card would you like to apply for?',
          'chat_credit_card_response': 'Credit card details...',
          'chat_savings_card_response': 'Savings card details...',
          'chat_debit_card_response': 'Debit card details...',
          'chat_default_response': 'How can I help you?',
          'chat_option_apply': 'Apply',
          'chat_option_details': 'Details',
          'chat_option_requirements': 'Requirements',
          'chat_option_open_account': 'Open Account',
          'chat_option_interest_rate': 'Interest Rate',
          'chat_option_features': 'Features',
        },
        'zh_CN': {
          // App
          'app_title': '计算器应用',
          'home': '首页',

          // Home Page
          'open_calculator': '打开计算器',
          'calculator_app_title': '计算器应用',

          // Calculator Page
          'calculator': '计算器',
          'error': '错误',
          'clear': 'C',
          'sign': '±',
          'percent': '%',
          'divide': '÷',
          'multiply': '×',
          'subtract': '-',
          'add': '+',
          'equals': '=',
          'zero': '0',
          'one': '1',
          'two': '2',
          'three': '3',
          'four': '4',
          'five': '5',
          'six': '6',
          'seven': '7',
          'eight': '8',
          'nine': '9',
          'dot': '.',

          // Chat Page
          'chat_title': 'AI聊天',
          'chat_ai_name': '小云',
          'chat_ai_title': 'AI智能助理',
          'chat_welcome_message': '请问您要办理什么卡?',
          'chat_option_credit_card': '信用卡',
          'chat_option_debit_card': '借记卡',
          'chat_option_savings_card': '储蓄卡',
          'chat_ai_disclaimer': '内容由AI生成，具体以实际情况为准',
          'chat_input_placeholder': '请输入您要咨询的问题',
          'chat_what_card_question': '请问您要办理什么卡?',
          'chat_credit_card_response': '信用卡业务介绍...',
          'chat_savings_card_response': '储蓄卡业务介绍...',
          'chat_debit_card_response': '借记卡业务介绍...',
          'chat_default_response': '您好，我可以帮您办理银行卡业务。',
          'chat_option_apply': '立即申请',
          'chat_option_details': '了解详情',
          'chat_option_requirements': '申请条件',
          'chat_option_open_account': '开户',
          'chat_option_interest_rate': '利率查询',
          'chat_option_features': '功能特点',
        },
      };
}
